version: "2.4"
services:
  db:
    image: postgres:12.2
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../
      dockerfile: ./build/api/Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always

  db-migration:
    build:
      context: ../../
      dockerfile: ./build/migration/Dockerfile
    container_name: migrations
    depends_on:
      api:
        condition: service_started
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  db:
