version: "3.9"
services:
  db:
    image: postgres:12.2
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: ../../
      dockerfile: ./build/api/Dockerfile
    container_name: api
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: 3000
    restart: always
